version: "3"
services:

    db:
        hostname: db
        image: mysql:latest
        environment:
            - MYSQL_DATABASE=telebar
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes

    server:
        hostname: server
        build: .
        ports:
            - 0.0.0.0:7707:7707
        depends_on:
            - db
        environment:
            - DB_USER=admin
            - DB_PASSWORD=password
            - DB_PORT=3306
            - DB_NAME=telebar
        command: bash -c "make server && ./server"
