#ifndef _TELEBAR_CONFIGURATION_GAMECONFIGURATION_
#define _TELEBAR_CONFIGURATION_GAMECONFIGURATION_

#define GAME_ACTION_START_GAME "startGame"
#define GAME_ACTION_GET_BOARD "getBoard"
#define GAME_ACTION_GET_MESSAGE "getMessage"
#define GAME_ACTION_SEND_MESSAGE "newMessage"
#define GAME_ACTION_SEND_BOARD_MOVEMENT "setBoard"
#define GAME_ACTION_GET_UPDATE "getInfo"

#define GAME_EVENT_THE_GAME_HAS_STARTED "theGameHasStarted"
#define GAME_EVENT_NEW_MESSAGE "newMessage"

#endif