#ifndef _TELEBAR_CONFIGURATION_SERVERCONFIGURATION_
#define _TELEBAR_CONFIGURATION_SERVERCONFIGURATION_

#define DB_NAME "server.db"

#define MIN_PLAYERS 2
#define MAX_PLAYERS 6

#define SERVER_ACTION_LOGIN "login"
#define SERVER_ACTION_REGISTER "register"

#endif